### ISSUE TITLE
The extension does not work

### ISSUE THREAD

**Issue by minherz** [vchlum/notification-timeout#7]
Hello,
I have installed extension on my GNOME 43.6 (OS Linux Debian Rodete) and it has no effect at all.
I tried switching two cnobs to keep both of them ON and both of the OF. The notification window remains forever.
I run it together with another extension that controls the location of the window ([Notification Banner Reload][1]).
The only thing that I did not do yet is to restart OS after I installed the extension.

[1]: https://github.com/marcinjakubowski/notification-position-reloaded

**Comment by vchlum** [comment]
Hi! On Gnome < 45, this extension and Notification Banner Reloaded replace the same function `MessageTray.MessageTray.prototype._showNotification`, which is why this extension does not work. In the Gnome 45 version of Notification Timeout, I changed the shared function to use another one but can not test it because NBF crashes on Gnome 45 for me. (even with Notification timeout disabled) So I can not tell you if the two extensions can work together.

I suggest you decide to use only one of these two extensions.

**Comment by minherz** [comment]
Thank you for the update. My issue is that the Banner Reload does not provide auto-hide functionality. I will open a FR about that.

**Comment by minherz** [comment]
Just for the reference: https://github.com/marcinjakubowski/notification-position-reloaded/issues/23
